export { default as HomeHeader } from './homeHeader'
export { default as HomeContent } from './homeContent'
export { default as NavRegister } from './navRegister'
export { default as NavBranch } from './navBranch'
export { default as BranchDetailContent } from './branchDetailContent'
export { default as ListBranchContent} from './listBranchContent'
export { default as RegisterHeader } from './registerHeader'
export { default as RegisterStepOne } from './registerStepOne'
export { default as RegisterStepTwo } from './registerStepTwo'
export { default as RegisterStepFinal } from './registerStepFinal'
export { default as BtnRegister } from './btnRegister'