export { default as Brand } from './brand'
export { default as Branchs } from './branchs'
export { default as BranchsAdd } from './branchsAdd'
export { default as BranchsContact } from './branchsContact'

export { default as InputBox } from './inputBox'
export { default as InputBoxV2 } from './inputBox_v2'
export { default as InputBoxV3 } from './inputBox_v3'

export { default as UserNav } from './userNav'
export { default as UserInfo } from './userInfo'
export { default as CreditCard } from './creditCard'
export { default as PointPacket } from './pointPacket'
export { default as Promotion } from './promotion'
export { default as Gift } from './gift'
export { default as SupStaff } from './supStaff'